name: Create Nightly Release

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
    push:
        branches:
            - Main
    pull_request:
        branches:
            - Main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3
        - name: Nightly Release
          run: |
            sudo apt install libfuse2
            make gitbuilds
            
        - uses: andelf/nightly-release@main
          with:
            tag_name: nightly_release
            name: "Rit Nightly Release $$ (commit: $GITHUB_SHA)"
            prerelease: true
            body: "This is a nightly release. May or may not work."
            files: build/dist/*

